openapi: 3.0.4
info:
  title: Random Quote
  description: Random Quote is a simple tool for getting random quotes. It returns a random quote from a collection of quotes.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/randomquote:
    get:
      summary: Get Random Quote
      description: Random Quote is a simple tool for getting random quotes. It returns a random quote from a collection of quotes.
      operationId: randomquote
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  quote: Everyone can taste success when the going is easy, but few know how to taste victory when times get tough.
                  author: Byron Pulsifer
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
